#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" <<-EOSQL
    CREATE USER $SENSOR_DB_USER WITH PASSWORD '$SENSOR_DB_PASSWORD';
    CREATE DATABASE $SENSOR_DB_NAME;
    \c $SENSOR_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $SENSOR_DB_NAME TO $SENSOR_DB_USER;
    GRANT ALL PRIVILEGES ON SCHEMA public TO $SENSOR_DB_USER;
EOSQL